<?PHP
/*****************************************************************************/
/* Iw DB: Icewars geoscan and sitter database                                */
/* Open-Source Project started by Robert Riess (robert@riess.net)            */
/* Software Version: Iw DB 1.00                                              */
/* ========================================================================= */
/* Software Distributed by:    http://lauscher.riess.net/iwdb/               */
/* Support, News, Updates at:  http://lauscher.riess.net/iwdb/               */
/* ========================================================================= */
/* Copyright (c) 2004 Robert Riess - All Rights Reserved                     */
/*****************************************************************************/
/* This program is free software; you can redistribute it and/or modify it   */
/* under the terms of the GNU General Public License as published by the     */
/* Free Software Foundation; either version 2 of the License, or (at your    */
/* option) any later version.                                                */
/*                                                                           */
/* This program is distributed in the hope that it will be useful, but       */
/* WITHOUT ANY WARRANTY; without even the implied warranty of                */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General */
/* Public License for more details.                                          */
/*                                                                           */
/* The GNU GPL can be found in LICENSE in this directory                     */
/*****************************************************************************/
/* This file was automatically generated by an installation routine.         */
/*****************************************************************************/

$desc_m_polkarte="Anzeige einer Universumskarte mit allen Allianzstati";
// verwendete Allianzstatuse  
$config_polstat = array(); 
$config_polstat['1v1']="own"; 
$config_polstat['1v2']="wing"; 
$config_polstat['1v3']="Wing"; 
$config_polstat['2v1']="VB";   
$config_polstat['2v2']="iVB";  
$config_polstat['2v3']="keineAhnung"; 
$config_polstat['3v1']="Krieg";   
$config_polstat['3v2']="hmmm";   
$config_polstat['3v3']="waswasi"; 
// verwendete Farben 
$config_polcolor = array(); $config_polcolor['nichts'] = "#FFFFFF"; 
$config_polcolor['1allein'] = "#C4F493";  
$config_polcolor['2allein'] = "#4A71D5";  
$config_polcolor['3allein'] = "#E84528";  
$config_polcolor['1und2'] = "#191970";    
$config_polcolor['1und3'] = "#FF7F24";    
$config_polcolor['2und3'] = "#FA8072";     
$config_polcolor['1und2und3'] = "#FF7F24"; 

?>
