<?PHP
/*****************************************************************************/
/* Iw DB: Icewars geoscan and sitter database                                */
/* Open-Source Project started by Robert Riess (robert@riess.net)            */
/* Software Version: Iw DB 1.00                                              */
/* ========================================================================= */
/* Software Distributed by:    http://lauscher.riess.net/iwdb/               */
/* Support, News, Updates at:  http://lauscher.riess.net/iwdb/               */
/* ========================================================================= */
/* Copyright (c) 2004 Robert Riess - All Rights Reserved                     */
/*****************************************************************************/
/* This program is free software; you can redistribute it and/or modify it   */
/* under the terms of the GNU General Public License as published by the     */
/* Free Software Foundation; either version 2 of the License, or (at your    */
/* option) any later version.                                                */
/*                                                                           */
/* This program is distributed in the hope that it will be useful, but       */
/* WITHOUT ANY WARRANTY; without even the implied warranty of                */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General */
/* Public License for more details.                                          */
/*                                                                           */
/* The GNU GPL can be found in LICENSE in this directory                     */
/*****************************************************************************/
/* This file was automatically generated by an installation routine.         */
/*****************************************************************************/

$desc_m_transferliste="In der Buddler-Statistik werden die an die Fleeter transferierten Rohstoffe erfasst und statistisch aufbereitet.";

// Faktoren zur Punkteberechnung
$fakt_eisen                 =   2;   // Default:  2
$fakt_stahl                 =   5;   // Default:  5
$fakt_chem                  =   2;   // Default:  2
$fakt_vv4a                  =  11;   // Default: 11
$fakt_eis                   =   2;   // Default:  2
$fakt_wasser                =   6;   // Default:  6
$fakt_energie               =   1;   // Default:  1
$fakt_volk                  =   0;   // Default:  0
// In der Buddlerübersicht Grafik anzeigen (True / False ) ?
$show_buddler_graph         =  True;
// Groesse des Diagramms
$graph_xsize                = 750;
$graph_ysize                = 200;
// Raender bis zu den Achsen
// Wenn mehr als 1 Buddler angezeigt muss eine Farblegende gezeichnet werden
// die mehr Platz benoetigt
$config_borderleft          =  50;
$config_borderright         =  50;
$config_bordertop           =  20;
$config_borderbottom        =  35;
$config_borderright_legende = 150;
// Typ des Diagramms ('l' => Linien / 'b' => Balken )
$buddler_graph_typ          = 'l';
// Standard Sortierrichtung Gesamttransferliste
$default_order              = 'punkte';
$default_ordered            = 'desc';
// Standard Sortierrichtung Buddlertransferliste
$default_buddler_order      = 'zeitmarke';
$default_buddler_ordered    = 'desc';

?>
