<?PHP
/*****************************************************************************/
/* Iw DB: Icewars geoscan and sitter database                                */
/* Open-Source Project started by Robert Riess (robert@riess.net)            */
/* Software Version: Iw DB 1.00                                              */
/* ========================================================================= */
/* Software Distributed by:    http://lauscher.riess.net/iwdb/               */
/* Support, News, Updates at:  http://lauscher.riess.net/iwdb/               */
/* ========================================================================= */
/* Copyright (c) 2004 Robert Riess - All Rights Reserved                     */
/*****************************************************************************/
/* This program is free software; you can redistribute it and/or modify it   */
/* under the terms of the GNU General Public License as published by the     */
/* Free Software Foundation; either version 2 of the License, or (at your    */
/* option) any later version.                                                */
/*                                                                           */
/* This program is distributed in the hope that it will be useful, but       */
/* WITHOUT ANY WARRANTY; without even the implied warranty of                */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General */
/* Public License for more details.                                          */
/*                                                                           */
/* The GNU GPL can be found in LICENSE in this directory                     */
/*****************************************************************************/
/* This file was automatically generated by an installation routine.         */
/*****************************************************************************/

$desc_m_universe="Dieses Modul f&uuml;gt eine &Uuml;bersicht f&uuml;r das bekannte Universum hinzu.";
$config_lineheight   = 22; // vertical size of a single system (min of fontheight + 2)
$config_linewidth    =  3; // horizontal size of a single system (min 2)

$config_borderleft   = 50; // min 25
$config_borderright  = 25;
$config_bordertop    = 40; // min 6 + $config_lineheight
$config_borderbottom = 25;

$config_font_to_use  =  2;

?>
